[package]
name = "rustflut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
itertools = "0.12.0"
rand = "0.8.5"
rayon = "1.8.0"
rusttype = "0.9.3"


