[package]
name = "rustflut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
fontdue = "0.8.0"
rand = "0.8.5"
rayon = "1.8.0"


